modLoader = "javafml"
loaderVersion = "[3,)"
issueTrackerURL = "https://github.com/19Phin/Partial-Hearts/issues"
license = "MIT"

[[mods]]
modId = "partialhearts"
version = "${version}"
displayName = "Partial Hearts"
authors = "DialingSpoon"
description = '''
Exact health displayed with fractions of a heart.
'''
logoFile = "assets/partialhearts/icon.png"

[[dependencies.partialhearts]]
modId = "neoforge"
type = "required"
versionRange = "(20.4,20.6)"
ordering = "NONE"
side = "BOTH"

[[dependencies.partialhearts]]
modId = "minecraft"
type = "required"
versionRange = "(1.20.4,1.20.6)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "partialhearts.mixins.json"
[[mixins]]
config = "partialhearts.neo.mixins.json"